### ISSUE TITLE
Add typography as specified in the Figma style sheet

### ISSUE THREAD

**Issue by JithinKS97** [picturama-defi/frontend#9]
<img width="532" alt="Screenshot 2021-11-03 at 9 21 55 AM" src="https://user-images.githubusercontent.com/19987520/140007845-f9986a03-e27d-42bd-b905-868e07268da9.png">

**Comment by sanjayrjs16** [comment]
PR for this issues:
https://github.com/picturama-defi/frontend/pull/13
